### ISSUE TITLE
[gulp] consider just emitting 'end' if no files provided

### ISSUE THREAD

**Issue by brendankenny** [ChadKillingsworth/closure-compiler-npm#3]
Thanks for putting this together and landing the changes needed in the compiler itself!

Right now the compiler will be [invoked with an empty list](https://github.com/ChadKillingsworth/closure-compiler-npm/blob/0ef48c12dbb75c18770535af54a8ca95030ad93c/lib/gulp/index.js#L79) if no files are provided, however this means that it won't work with gulp plugins like [gulp-newer](https://github.com/tschaub/gulp-newer) when trying to avoid unnecessary compiles.

One option is to instead just `this.emit('end')` and return, though maybe there are cases in which it's preferred to compile and generate *something*, even when no source files are provided?

**Comment by ChadKillingsworth** [comment]
It is very intentional. Source file input globs can be provided directly to the compiler:

 * https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/test/gulp.js#L211
 * https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/test/gulp.js#L246
 * https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/test/grunt.js#L193

Using existing plugins in advanced use case scenarios, I have had to work around the fact many times that the compiler is only invoked when conditions set by the plugin are met. And these conditions don't always hold true.

**Comment by brendankenny** [comment]
arg, that's the case I didn't think of. Do you know of a good way to handle the `gulp-newer

**Comment by ChadKillingsworth** [comment]
I would think something like [gulp-if](https://github.com/robrich/gulp-if) could handle that case. You just might have to figure out how to get the condition properly set.

**Comment by brendankenny** [comment]
gulp-if always runs the conditional stream, even if no files pass the conditional (and even if there are no files passed to gulp-if at all), so the end result is the same, unfortunately.

Before I write my own plugin, just wanted to check if the case of emitting end on `fileList.length === 0 && !compilationOptions.js` also doesn't work?

**Comment by ChadKillingsworth** [comment]
Testing arguments gets extremely difficult. Specifically due to https://github.com/ChadKillingsworth/closure-compiler-npm#advanced-usage-with-arguments-array-1

That's basically the "leave me alone and do what I say" use case. I also have to account for the fact that the grunt plugin is simply a wrapper for the gulp plugin: https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/lib/grunt/index.js#L75

**Comment by ChadKillingsworth** [comment]
If you want to create a PR such that the gulp plugin initialization takes an option, that might work:

```js
var closureCompiler = require('google-closure-compiler').gulp({
  requireStreamInput: true
});
```
